### ISSUE TITLE
Move `Size` here?

### ISSUE THREAD

**Issue by devmotion** [JuliaArrays/StaticArraysCore.jl#12]
I wonder if it would be possible to move `Size` to this package? For instance, by moving (parts of) https://github.com/JuliaArrays/StaticArrays.jl/blob/ec2dc5ee8559e4d3125e4a392c050bfa27b8bfe1/src/traits.jl?

This was already discussed briefly in #3.
`Size` is currently mentioned in the docstring of `similar_type` even though it is not available in StaticArraysCore.
If it would be available also downstream code such as in https://github.com/JuliaDiff/DiffResults.jl/pull/22 could be simplified.

**Comment by mateuszbaran** [comment]
Yes, I think that would be a good idea. I will try doing it today or tomorrow.
