### ISSUE TITLE
Moving `length` here

### ISSUE THREAD

**Issue by mcabbott** [JuliaArrays/StaticArraysCore.jl#14]
For https://github.com/JuliaDiff/ForwardDiff.jl/pull/599 to work, `length(::Type{StaticArraysCore.SMatrix{3, 3, Float64, 9}})` needs to be defined here in StaticArraysCore.

The present definition is:

https://github.com/JuliaArrays/StaticArrays.jl/blob/f7b8ed21c946fef2e9ecb00d7a27bccdd2623976/src/abstractarray.jl#L1-L2

which needs 

https://github.com/JuliaArrays/StaticArrays.jl/blob/28e0482ba006bfb9a4a4f19dbf8b3096b2611497/src/StaticArrays.jl#L71-L86

which depends on LinearAlgebra. 

What should happen? This core package has no dependencies right now. Should it gain LinearAlgebra just for this? Otherwise it could just define `length` for a smaller set of types, and let the main package extend that. I think that would be sufficient for ForwardDiff, whose generated functions e.g. here https://github.com/JuliaDiff/ForwardDiff.jl/blob/c6dc2098b5201943cdb8433ee963078e6dcc7900/src/apiutils.jl#L21-L25 accept only `x::StaticArray`, never Diagonal(StaticVector) etc.

**Comment by mateuszbaran** [comment]
I think it would be the easiest if ForwardDiff just used `tuple_prod` instead of `length` like here: https://github.com/JuliaArrays/StaticArraysCore.jl/blob/33f4dada9a6e19dddc4eb0d65807d4185f4ed9a0/src/StaticArraysCore.jl#L117 .

**Comment by mcabbott** [comment]
Thanks, that indeed solves the problem. Done here: https://github.com/JuliaDiff/ForwardDiff.jl/pull/599/commits/f3afe136cd1e62bfff4219e7918685745a011ea9

Maybe the next one is harder. While #5 moved `similar_type` here, its methods are all from the main package, and these seem to be called within `@generated` code, leading to:

```julia
StaticArraysCore.MArray: Error During Test at /Users/me/.julia/dev/ForwardDiff/test/GradientTest.jl:87
  Got exception outside of a @test
  MethodError: no method matching similar_type(::Type{StaticArraysCore.MMatrix{3, 3, Float64, 9}}, ::Type{ForwardDiff.Dual{ForwardDiff.Tag{typeof(prod), Float64}, Float64, 9}})
  The applicable method may be too new: running in world age 33438, while current world is 33489.
  
  Closest candidates are:
    similar_type(::Type{SA}, ::Type{T}, ::StaticArraysCore.Size{S}) where {SA<:StaticArraysCore.MArray, T, S} (method too new to be called from this world context.)
     @ StaticArrays ~/.julia/packages/StaticArrays/B0HhH/src/abstractarray.jl:76
    similar_type(::Type{SA}, ::Type{T}) where {SA<:(Union{LinearAlgebra.Adjoint{T, <:Union{StaticArraysCore.StaticArray{Tuple{var"#s2"}, T, 1} where var"#s2", StaticArraysCore.StaticArray{Tuple{var"#s3", var"#s4"}, T, 2} where {var"#s3", var"#s4"}}}, LinearAlgebra.Diagonal{T, <:StaticArraysCore.StaticArray...  (method too new to be called from this world context.)
     @ StaticArrays ~/.julia/packages/StaticArrays/B0HhH/src/abstractarray.jl:37
    similar_type(::Type{A}, ::Type{T}, ::StaticArraysCore.Size{S}) where {A<:AbstractArray, T, S} (method too new to be called from this world context.)
     @ StaticArrays ~/.julia/packages/StaticArrays/B0HhH/src/abstractarray.jl:73
    ...
```
