### ISSUE TITLE
Could the definition of `similar_type` move here?

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaArrays/StaticArraysCore.jl#3]
https://github.com/SciML/LabelledArrays.jl/pull/122

It really should be in Base, but 🤷

**Comment by mateuszbaran** [comment]
Yes, that's reasonable.

**Comment by mateuszbaran** [comment]
I guess you also need the `Size` type and all `similar_type` methods it enables?

**Comment by ChrisRackauckas** [comment]
I don't, https://github.com/SciML/LabelledArrays.jl/pull/122/files#diff-918dda16160ab68d9766c22082a5c3463aef402c63fdf25244313c9f2bde525eR40

but I don't know if that's common. I worked around any Size issues like https://github.com/SciML/LabelledArrays.jl/pull/122/files#diff-918dda16160ab68d9766c22082a5c3463aef402c63fdf25244313c9f2bde525eR162

**Comment by mateuszbaran** [comment]
OK, so #5 is enough?

**Comment by devmotion** [comment]
This would be useful for ForwardDiff as well, it seems, as it uses `similar_type` in its implementations for `StaticArray`s.

Ref: https://github.com/JuliaDiff/ForwardDiff.jl/issues/591

**Comment by N5N3** [comment]
> I don't, https://github.com/SciML/LabelledArrays.jl/pull/122/files#diff-918dda16160ab68d9766c22082a5c3463aef402c63fdf25244313c9f2bde525eR40
> 
> but I don't know if that's common. I worked around any Size issues like https://github.com/SciML/LabelledArrays.jl/pull/122/files#diff-918dda16160ab68d9766c22082a5c3463aef402c63fdf25244313c9f2bde525eR162

@ChrisRackauckas looks like you still need the `Size` struct?
```julia
function StaticArrays.similar_type(::Type{SLArray{S, T, N, L, Syms}}, ::Type{NewElType},
                                   ::Size{NewSize}) where {S, T, N, L, Syms, NewElType, # used here
                                                           NewSize}
```

**Comment by ChrisRackauckas** [comment]
It can be worked around.

**Comment by N5N3** [comment]
Do you mean
```julia
function StaticArrays.similar_type(::Type{SLArray{S, T, N, L, Syms}}, ::Type{NewElType}, sz) where {S, T, N, L, Syms, NewElType}
```
?
This would cause ambiguity as we have
```julia
  similar_type(::Type{A}, ::Type{T}, s::Size{S}) where {A<:AbstractArray, T, S}
```

**Comment by mcabbott** [comment]
What's the work-around? 

The linked package still loads StaticArrays, so doesn't benefit from this:
https://github.com/SciML/LabelledArrays.jl/blob/master/Project.toml#L13
